micronaut:
  application:
    name: MNRestExemplar
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  codec:
    json:
      additional-types: 'application/problem+json'

netty:
  default:
    allocator:
      max-order: 3

problem:
  enabled: true
  stack-trace: false

liquibase:
  datasources:
    default:
      enabled: true
      change-log: classpath:db/liquibase-changelog.xml

datasources:
  default:
#    url: jdbc:mysql://localhost:3306/db
#    username: root
#    password: ''
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES
    schema-generate: NONE

endpoints:
  health:
    enabled: true
    sensitive: false              # TODO Change to make secure
    details-visible: ANONYMOUS
  info:
    enabled: true
    sensitive: false              # TODO Change to make secure
    build:
      enabled: true
  routes:
    enabled: true
    sensitive: false              # TODO Change to make secure
  refresh:
    enabled: true
    sensitive: false              # TODO Change to make secure
  loggers:
    enabled: true
    sensitive: false              # TODO Change to make secure
    write-sensitive: false
#  metrics:
#    enabled: true                 # TODO Change to make secure
#    sensitive: false
  liquibase:
    enabled: true
    sensitive: false