micronaut:
  application:
    name: mn4-rest-exemplar
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: mysql
    dialect: MYSQL
liquibase:
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.xml
